interface SessionFile {
    void SessionFile();

    boolean IsSessionFile(long size, [Const] VoidPtr data);

    long GetDeviceId();
    [Ref] SessionFile SetDeviceId(long deviceId);

    [Const] VoidPtr GetMetadata();
    long GetMetadataSize();
    [Ref] SessionFile SetMetadata(long size, [Const] VoidPtr data);

    [Const] VoidPtr GetNor();
    long GetNorSize();
    [Ref] SessionFile SetNor(long size, [Const] VoidPtr data);

    [Const] VoidPtr GetNand();
    long GetNandSize();
    [Ref] SessionFile SetNand(long size, [Const] VoidPtr data);

    [Const] VoidPtr GetMemory();
    long GetMemorySize();
    [Ref] SessionFile SetMemory(long size, [Const] VoidPtr data);

    [Const] VoidPtr GetSavestate();
    long GetSavestateSize();
    [Ref] SessionFile SetSavestate(long size, [Const] VoidPtr data);

    boolean Serialize();
    [Const] VoidPtr GetSerializedSession();
    long GetSerializedSessionSize();

    boolean Deserialize(long Size, [Const] VoidPtr data);
};