/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "networking.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Address, Address, AUTO)


PB_BIND(MsgSocketOpenRequest, MsgSocketOpenRequest, AUTO)


PB_BIND(MsgSocketOpenResponse, MsgSocketOpenResponse, AUTO)


PB_BIND(MsgSocketBindRequest, MsgSocketBindRequest, AUTO)


PB_BIND(MsgSocketBindResponse, MsgSocketBindResponse, AUTO)


PB_BIND(MsgSocketAddrRequest, MsgSocketAddrRequest, AUTO)


PB_BIND(MsgSocketAddrResponse, MsgSocketAddrResponse, AUTO)


PB_BIND(MsgSocketSendRequest, MsgSocketSendRequest, AUTO)


PB_BIND(MsgSocketSendResponse, MsgSocketSendResponse, AUTO)


PB_BIND(MsgSocketReceiveRequest, MsgSocketReceiveRequest, AUTO)


PB_BIND(MsgSocketReceiveResponse, MsgSocketReceiveResponse, AUTO)


PB_BIND(MsgSocketCloseRequest, MsgSocketCloseRequest, AUTO)


PB_BIND(MsgSocketCloseResponse, MsgSocketCloseResponse, AUTO)


PB_BIND(MsgGetHostByNameRequest, MsgGetHostByNameRequest, 2)


PB_BIND(MsgGetHostByNameResponse, MsgGetHostByNameResponse, 2)


PB_BIND(MsgGetServByNameRequest, MsgGetServByNameRequest, AUTO)


PB_BIND(MsgGetServByNameResponse, MsgGetServByNameResponse, AUTO)


PB_BIND(MsgSocketConnectRequest, MsgSocketConnectRequest, AUTO)


PB_BIND(MsgSocketConnectResponse, MsgSocketConnectResponse, AUTO)


PB_BIND(MsgSelectRequest, MsgSelectRequest, AUTO)


PB_BIND(MsgSelectResponse, MsgSelectResponse, AUTO)


PB_BIND(MsgInvalidRequestResponse, MsgInvalidRequestResponse, AUTO)


PB_BIND(MsgSettingGetRequest, MsgSettingGetRequest, AUTO)


PB_BIND(MsgSettingGetResponse, MsgSettingGetResponse, 2)


PB_BIND(MsgSocketOptionSetRequest, MsgSocketOptionSetRequest, AUTO)


PB_BIND(MsgSocketOptionSetResponse, MsgSocketOptionSetResponse, AUTO)


PB_BIND(MsgSocketOptionGetRequest, MsgSocketOptionGetRequest, AUTO)


PB_BIND(MsgSocketOptionGetResponse, MsgSocketOptionGetResponse, AUTO)


PB_BIND(MsgSocketListenRequest, MsgSocketListenRequest, AUTO)


PB_BIND(MsgSocketListenResponse, MsgSocketListenResponse, AUTO)


PB_BIND(MsgSocketAcceptRequest, MsgSocketAcceptRequest, AUTO)


PB_BIND(MsgSocketAcceptResponse, MsgSocketAcceptResponse, AUTO)


PB_BIND(MsgRequest, MsgRequest, 2)


PB_BIND(MsgResponse, MsgResponse, 2)



