/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_NETWORKING_PB_H_INCLUDED
#define PB_NETWORKING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Address {
    uint32_t ip;
    int32_t port;
} Address;

typedef struct _MsgSocketOpenRequest {
    uint32_t type;
    uint32_t protocol;
} MsgSocketOpenRequest;

typedef struct _MsgSocketOpenResponse {
    int32_t handle;
    int32_t err;
} MsgSocketOpenResponse;

typedef struct _MsgSocketBindRequest {
    int32_t handle;
    Address address;
    int32_t timeout;
} MsgSocketBindRequest;

typedef struct _MsgSocketBindResponse {
    int32_t err;
} MsgSocketBindResponse;

typedef struct _MsgSocketAddrRequest {
    int32_t handle;
    bool requestAddressLocal;
    bool requestAddressRemote;
    int32_t timeout;
} MsgSocketAddrRequest;

typedef struct _MsgSocketAddrResponse {
    bool has_addressLocal;
    Address addressLocal;
    bool has_addressRemote;
    Address addressRemote;
    int32_t err;
} MsgSocketAddrResponse;

typedef struct _MsgSocketSendRequest {
    int32_t handle;
    pb_callback_t data;
    uint32_t flags;
    bool has_address;
    Address address;
    int32_t timeout;
} MsgSocketSendRequest;

typedef struct _MsgSocketSendResponse {
    int32_t err;
    int32_t bytesSent;
} MsgSocketSendResponse;

typedef struct _MsgSocketReceiveRequest {
    int32_t handle;
    uint32_t flags;
    int32_t timeout;
    uint32_t maxLen;
    bool addressRequested;
} MsgSocketReceiveRequest;

typedef struct _MsgSocketReceiveResponse {
    int32_t err;
    pb_callback_t data;
    bool has_address;
    Address address;
} MsgSocketReceiveResponse;

typedef struct _MsgSocketCloseRequest {
    int32_t handle;
    int32_t timeout;
} MsgSocketCloseRequest;

typedef struct _MsgSocketCloseResponse {
    int32_t err;
} MsgSocketCloseResponse;

typedef struct _MsgGetHostByNameRequest {
    char name[256];
} MsgGetHostByNameRequest;

typedef struct _MsgGetHostByNameResponse {
    char name[256];
    bool has_alias;
    char alias[256];
    pb_size_t addresses_count;
    uint32_t addresses[3];
    int32_t err;
} MsgGetHostByNameResponse;

typedef struct _MsgGetServByNameRequest {
    char name[16];
    char protocol[4];
} MsgGetServByNameRequest;

typedef struct _MsgGetServByNameResponse {
    uint32_t port;
    int32_t err;
} MsgGetServByNameResponse;

typedef struct _MsgSocketConnectRequest {
    int32_t handle;
    Address address;
    int32_t timeout;
} MsgSocketConnectRequest;

typedef struct _MsgSocketConnectResponse {
    int32_t err;
} MsgSocketConnectResponse;

typedef struct _MsgSelectRequest {
    uint32_t width;
    uint32_t readFDs;
    uint32_t writeFDs;
    uint32_t exceptFDs;
    int32_t timeout;
} MsgSelectRequest;

typedef struct _MsgSelectResponse {
    uint32_t readFDs;
    uint32_t writeFDs;
    uint32_t exceptFDs;
    int32_t err;
} MsgSelectResponse;

typedef struct _MsgInvalidRequestResponse {
    bool tag;
} MsgInvalidRequestResponse;

typedef struct _MsgSettingGetRequest {
    uint32_t setting;
} MsgSettingGetRequest;

typedef struct _MsgSettingGetResponse {
    pb_size_t which_value;
    union {
        uint32_t uint32val;
        uint32_t uint8val;
        char strval[256];
    } value;
    int32_t err;
} MsgSettingGetResponse;

typedef PB_BYTES_ARRAY_T(40) MsgSocketOptionSetRequest_bufval_t;
typedef struct _MsgSocketOptionSetRequest {
    int32_t handle;
    uint32_t level;
    uint32_t option;
    int32_t timeout;
    pb_size_t which_value;
    union {
        int32_t intval;
        MsgSocketOptionSetRequest_bufval_t bufval;
    } value;
} MsgSocketOptionSetRequest;

typedef struct _MsgSocketOptionSetResponse {
    int32_t err;
} MsgSocketOptionSetResponse;

typedef struct _MsgSocketOptionGetRequest {
    int32_t handle;
    uint32_t level;
    uint32_t option;
    int32_t timeout;
} MsgSocketOptionGetRequest;

typedef PB_BYTES_ARRAY_T(40) MsgSocketOptionGetResponse_bufval_t;
typedef struct _MsgSocketOptionGetResponse {
    int32_t err;
    pb_size_t which_value;
    union {
        int32_t intval;
        MsgSocketOptionGetResponse_bufval_t bufval;
    } value;
} MsgSocketOptionGetResponse;

typedef struct _MsgSocketListenRequest {
    int32_t handle;
    int32_t backlog;
    int32_t timeout;
} MsgSocketListenRequest;

typedef struct _MsgSocketListenResponse {
    int32_t err;
} MsgSocketListenResponse;

typedef struct _MsgSocketAcceptRequest {
    int32_t handle;
    int32_t timeout;
} MsgSocketAcceptRequest;

typedef struct _MsgSocketAcceptResponse {
    int32_t handle;
    Address address;
    int32_t err;
} MsgSocketAcceptResponse;

typedef struct _MsgSocketShutdownRequest {
    int32_t handle;
    int32_t direction;
    int32_t timeout;
} MsgSocketShutdownRequest;

typedef struct _MsgSocketShutdownResponse {
    int32_t err;
} MsgSocketShutdownResponse;

typedef struct _MsgRequest {
    uint32_t id;
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        MsgSocketOpenRequest socketOpenRequest;
        MsgSocketBindRequest socketBindRequest;
        MsgSocketAddrRequest socketAddrRequest;
        MsgSocketSendRequest socketSendRequest;
        MsgSocketReceiveRequest socketReceiveRequest;
        MsgSocketCloseRequest socketCloseRequest;
        MsgGetHostByNameRequest getHostByNameRequest;
        MsgGetServByNameRequest getServByNameRequest;
        MsgSocketConnectRequest socketConnectRequest;
        MsgSelectRequest selectRequest;
        MsgSettingGetRequest settingGetRequest;
        MsgSocketOptionSetRequest socketOptionSetRequest;
        MsgSocketListenRequest socketListenRequest;
        MsgSocketAcceptRequest socketAcceptRequest;
        MsgSocketOptionGetRequest socketOptionGetRequest;
        MsgSocketShutdownRequest socketShutdownRequest;
    } payload;
} MsgRequest;

typedef struct _MsgResponse {
    uint32_t id;
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        MsgSocketOpenResponse socketOpenResponse;
        MsgSocketBindResponse socketBindResponse;
        MsgSocketAddrResponse socketAddrResponse;
        MsgSocketSendResponse socketSendResponse;
        MsgSocketReceiveResponse socketReceiveResponse;
        MsgSocketCloseResponse socketCloseResponse;
        MsgGetHostByNameResponse getHostByNameResponse;
        MsgGetServByNameResponse getServByNameResponse;
        MsgSocketConnectResponse socketConnectResponse;
        MsgSelectResponse selectResponse;
        MsgSettingGetResponse settingGetResponse;
        MsgSocketOptionSetResponse socketOptionSetResponse;
        MsgSocketListenResponse socketListenResponse;
        MsgSocketAcceptResponse socketAcceptResponse;
        MsgSocketOptionGetResponse socketOptionGetResponse;
        MsgSocketShutdownResponse socketShutdownResponse;
        MsgInvalidRequestResponse invalidRequestResponse;
    } payload;
} MsgResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Address_init_default                     {0, 0}
#define MsgSocketOpenRequest_init_default        {0, 0}
#define MsgSocketOpenResponse_init_default       {0, 0}
#define MsgSocketBindRequest_init_default        {0, Address_init_default, 0}
#define MsgSocketBindResponse_init_default       {0}
#define MsgSocketAddrRequest_init_default        {0, 0, 0, 0}
#define MsgSocketAddrResponse_init_default       {false, Address_init_default, false, Address_init_default, 0}
#define MsgSocketSendRequest_init_default        {0, {{NULL}, NULL}, 0, false, Address_init_default, 0}
#define MsgSocketSendResponse_init_default       {0, 0}
#define MsgSocketReceiveRequest_init_default     {0, 0, 0, 0, 0}
#define MsgSocketReceiveResponse_init_default    {0, {{NULL}, NULL}, false, Address_init_default}
#define MsgSocketCloseRequest_init_default       {0, 0}
#define MsgSocketCloseResponse_init_default      {0}
#define MsgGetHostByNameRequest_init_default     {""}
#define MsgGetHostByNameResponse_init_default    {"", false, "", 0, {0, 0, 0}, 0}
#define MsgGetServByNameRequest_init_default     {"", ""}
#define MsgGetServByNameResponse_init_default    {0, 0}
#define MsgSocketConnectRequest_init_default     {0, Address_init_default, 0}
#define MsgSocketConnectResponse_init_default    {0}
#define MsgSelectRequest_init_default            {0, 0, 0, 0, 0}
#define MsgSelectResponse_init_default           {0, 0, 0, 0}
#define MsgInvalidRequestResponse_init_default   {0}
#define MsgSettingGetRequest_init_default        {0}
#define MsgSettingGetResponse_init_default       {0, {0}, 0}
#define MsgSocketOptionSetRequest_init_default   {0, 0, 0, 0, 0, {0}}
#define MsgSocketOptionSetResponse_init_default  {0}
#define MsgSocketOptionGetRequest_init_default   {0, 0, 0, 0}
#define MsgSocketOptionGetResponse_init_default  {0, 0, {0}}
#define MsgSocketListenRequest_init_default      {0, 0, 0}
#define MsgSocketListenResponse_init_default     {0}
#define MsgSocketAcceptRequest_init_default      {0, 0}
#define MsgSocketAcceptResponse_init_default     {0, Address_init_default, 0}
#define MsgSocketShutdownRequest_init_default    {0, 0, 0}
#define MsgSocketShutdownResponse_init_default   {0}
#define MsgRequest_init_default                  {0, {{NULL}, NULL}, 0, {MsgSocketOpenRequest_init_default}}
#define MsgResponse_init_default                 {0, {{NULL}, NULL}, 0, {MsgSocketOpenResponse_init_default}}
#define Address_init_zero                        {0, 0}
#define MsgSocketOpenRequest_init_zero           {0, 0}
#define MsgSocketOpenResponse_init_zero          {0, 0}
#define MsgSocketBindRequest_init_zero           {0, Address_init_zero, 0}
#define MsgSocketBindResponse_init_zero          {0}
#define MsgSocketAddrRequest_init_zero           {0, 0, 0, 0}
#define MsgSocketAddrResponse_init_zero          {false, Address_init_zero, false, Address_init_zero, 0}
#define MsgSocketSendRequest_init_zero           {0, {{NULL}, NULL}, 0, false, Address_init_zero, 0}
#define MsgSocketSendResponse_init_zero          {0, 0}
#define MsgSocketReceiveRequest_init_zero        {0, 0, 0, 0, 0}
#define MsgSocketReceiveResponse_init_zero       {0, {{NULL}, NULL}, false, Address_init_zero}
#define MsgSocketCloseRequest_init_zero          {0, 0}
#define MsgSocketCloseResponse_init_zero         {0}
#define MsgGetHostByNameRequest_init_zero        {""}
#define MsgGetHostByNameResponse_init_zero       {"", false, "", 0, {0, 0, 0}, 0}
#define MsgGetServByNameRequest_init_zero        {"", ""}
#define MsgGetServByNameResponse_init_zero       {0, 0}
#define MsgSocketConnectRequest_init_zero        {0, Address_init_zero, 0}
#define MsgSocketConnectResponse_init_zero       {0}
#define MsgSelectRequest_init_zero               {0, 0, 0, 0, 0}
#define MsgSelectResponse_init_zero              {0, 0, 0, 0}
#define MsgInvalidRequestResponse_init_zero      {0}
#define MsgSettingGetRequest_init_zero           {0}
#define MsgSettingGetResponse_init_zero          {0, {0}, 0}
#define MsgSocketOptionSetRequest_init_zero      {0, 0, 0, 0, 0, {0}}
#define MsgSocketOptionSetResponse_init_zero     {0}
#define MsgSocketOptionGetRequest_init_zero      {0, 0, 0, 0}
#define MsgSocketOptionGetResponse_init_zero     {0, 0, {0}}
#define MsgSocketListenRequest_init_zero         {0, 0, 0}
#define MsgSocketListenResponse_init_zero        {0}
#define MsgSocketAcceptRequest_init_zero         {0, 0}
#define MsgSocketAcceptResponse_init_zero        {0, Address_init_zero, 0}
#define MsgSocketShutdownRequest_init_zero       {0, 0, 0}
#define MsgSocketShutdownResponse_init_zero      {0}
#define MsgRequest_init_zero                     {0, {{NULL}, NULL}, 0, {MsgSocketOpenRequest_init_zero}}
#define MsgResponse_init_zero                    {0, {{NULL}, NULL}, 0, {MsgSocketOpenResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Address_ip_tag                           1
#define Address_port_tag                         2
#define MsgSocketOpenRequest_type_tag            1
#define MsgSocketOpenRequest_protocol_tag        2
#define MsgSocketOpenResponse_handle_tag         1
#define MsgSocketOpenResponse_err_tag            2
#define MsgSocketBindRequest_handle_tag          1
#define MsgSocketBindRequest_address_tag         2
#define MsgSocketBindRequest_timeout_tag         3
#define MsgSocketBindResponse_err_tag            1
#define MsgSocketAddrRequest_handle_tag          1
#define MsgSocketAddrRequest_requestAddressLocal_tag 2
#define MsgSocketAddrRequest_requestAddressRemote_tag 3
#define MsgSocketAddrRequest_timeout_tag         4
#define MsgSocketAddrResponse_addressLocal_tag   1
#define MsgSocketAddrResponse_addressRemote_tag  2
#define MsgSocketAddrResponse_err_tag            3
#define MsgSocketSendRequest_handle_tag          1
#define MsgSocketSendRequest_data_tag            2
#define MsgSocketSendRequest_flags_tag           3
#define MsgSocketSendRequest_address_tag         4
#define MsgSocketSendRequest_timeout_tag         5
#define MsgSocketSendResponse_err_tag            1
#define MsgSocketSendResponse_bytesSent_tag      2
#define MsgSocketReceiveRequest_handle_tag       1
#define MsgSocketReceiveRequest_flags_tag        2
#define MsgSocketReceiveRequest_timeout_tag      3
#define MsgSocketReceiveRequest_maxLen_tag       4
#define MsgSocketReceiveRequest_addressRequested_tag 5
#define MsgSocketReceiveResponse_err_tag         1
#define MsgSocketReceiveResponse_data_tag        2
#define MsgSocketReceiveResponse_address_tag     3
#define MsgSocketCloseRequest_handle_tag         1
#define MsgSocketCloseRequest_timeout_tag        4
#define MsgSocketCloseResponse_err_tag           1
#define MsgGetHostByNameRequest_name_tag         1
#define MsgGetHostByNameResponse_name_tag        1
#define MsgGetHostByNameResponse_alias_tag       2
#define MsgGetHostByNameResponse_addresses_tag   3
#define MsgGetHostByNameResponse_err_tag         4
#define MsgGetServByNameRequest_name_tag         1
#define MsgGetServByNameRequest_protocol_tag     2
#define MsgGetServByNameResponse_port_tag        1
#define MsgGetServByNameResponse_err_tag         2
#define MsgSocketConnectRequest_handle_tag       1
#define MsgSocketConnectRequest_address_tag      2
#define MsgSocketConnectRequest_timeout_tag      3
#define MsgSocketConnectResponse_err_tag         1
#define MsgSelectRequest_width_tag               2
#define MsgSelectRequest_readFDs_tag             3
#define MsgSelectRequest_writeFDs_tag            4
#define MsgSelectRequest_exceptFDs_tag           5
#define MsgSelectRequest_timeout_tag             6
#define MsgSelectResponse_readFDs_tag            1
#define MsgSelectResponse_writeFDs_tag           2
#define MsgSelectResponse_exceptFDs_tag          3
#define MsgSelectResponse_err_tag                4
#define MsgInvalidRequestResponse_tag_tag        1
#define MsgSettingGetRequest_setting_tag         1
#define MsgSettingGetResponse_uint32val_tag      1
#define MsgSettingGetResponse_uint8val_tag       2
#define MsgSettingGetResponse_strval_tag         3
#define MsgSettingGetResponse_err_tag            4
#define MsgSocketOptionSetRequest_handle_tag     1
#define MsgSocketOptionSetRequest_level_tag      2
#define MsgSocketOptionSetRequest_option_tag     3
#define MsgSocketOptionSetRequest_timeout_tag    4
#define MsgSocketOptionSetRequest_intval_tag     6
#define MsgSocketOptionSetRequest_bufval_tag     7
#define MsgSocketOptionSetResponse_err_tag       1
#define MsgSocketOptionGetRequest_handle_tag     1
#define MsgSocketOptionGetRequest_level_tag      2
#define MsgSocketOptionGetRequest_option_tag     3
#define MsgSocketOptionGetRequest_timeout_tag    4
#define MsgSocketOptionGetResponse_err_tag       1
#define MsgSocketOptionGetResponse_intval_tag    3
#define MsgSocketOptionGetResponse_bufval_tag    4
#define MsgSocketListenRequest_handle_tag        1
#define MsgSocketListenRequest_backlog_tag       2
#define MsgSocketListenRequest_timeout_tag       3
#define MsgSocketListenResponse_err_tag          1
#define MsgSocketAcceptRequest_handle_tag        1
#define MsgSocketAcceptRequest_timeout_tag       2
#define MsgSocketAcceptResponse_handle_tag       1
#define MsgSocketAcceptResponse_address_tag      2
#define MsgSocketAcceptResponse_err_tag          3
#define MsgSocketShutdownRequest_handle_tag      1
#define MsgSocketShutdownRequest_direction_tag   2
#define MsgSocketShutdownRequest_timeout_tag     3
#define MsgSocketShutdownResponse_err_tag        1
#define MsgRequest_id_tag                        1
#define MsgRequest_socketOpenRequest_tag         2
#define MsgRequest_socketBindRequest_tag         3
#define MsgRequest_socketAddrRequest_tag         4
#define MsgRequest_socketSendRequest_tag         5
#define MsgRequest_socketReceiveRequest_tag      6
#define MsgRequest_socketCloseRequest_tag        7
#define MsgRequest_getHostByNameRequest_tag      8
#define MsgRequest_getServByNameRequest_tag      9
#define MsgRequest_socketConnectRequest_tag      10
#define MsgRequest_selectRequest_tag             11
#define MsgRequest_settingGetRequest_tag         12
#define MsgRequest_socketOptionSetRequest_tag    13
#define MsgRequest_socketListenRequest_tag       14
#define MsgRequest_socketAcceptRequest_tag       15
#define MsgRequest_socketOptionGetRequest_tag    16
#define MsgRequest_socketShutdownRequest_tag     17
#define MsgResponse_id_tag                       1
#define MsgResponse_socketOpenResponse_tag       2
#define MsgResponse_socketBindResponse_tag       3
#define MsgResponse_socketAddrResponse_tag       4
#define MsgResponse_socketSendResponse_tag       5
#define MsgResponse_socketReceiveResponse_tag    6
#define MsgResponse_socketCloseResponse_tag      7
#define MsgResponse_getHostByNameResponse_tag    8
#define MsgResponse_getServByNameResponse_tag    9
#define MsgResponse_socketConnectResponse_tag    10
#define MsgResponse_selectResponse_tag           11
#define MsgResponse_settingGetResponse_tag       12
#define MsgResponse_socketOptionSetResponse_tag  13
#define MsgResponse_socketListenResponse_tag     14
#define MsgResponse_socketAcceptResponse_tag     15
#define MsgResponse_socketOptionGetResponse_tag  16
#define MsgResponse_socketShutdownResponse_tag   17
#define MsgResponse_invalidRequestResponse_tag   255

/* Struct field encoding specification for nanopb */
#define Address_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   ip,                1) \
X(a, STATIC,   REQUIRED, INT32,    port,              2)
#define Address_CALLBACK NULL
#define Address_DEFAULT NULL

#define MsgSocketOpenRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   type,              1) \
X(a, STATIC,   REQUIRED, UINT32,   protocol,          2)
#define MsgSocketOpenRequest_CALLBACK NULL
#define MsgSocketOpenRequest_DEFAULT NULL

#define MsgSocketOpenResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, INT32,    err,               2)
#define MsgSocketOpenResponse_CALLBACK NULL
#define MsgSocketOpenResponse_DEFAULT NULL

#define MsgSocketBindRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, MESSAGE,  address,           2) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           3)
#define MsgSocketBindRequest_CALLBACK NULL
#define MsgSocketBindRequest_DEFAULT NULL
#define MsgSocketBindRequest_address_MSGTYPE Address

#define MsgSocketBindResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1)
#define MsgSocketBindResponse_CALLBACK NULL
#define MsgSocketBindResponse_DEFAULT NULL

#define MsgSocketAddrRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, BOOL,     requestAddressLocal,   2) \
X(a, STATIC,   REQUIRED, BOOL,     requestAddressRemote,   3) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           4)
#define MsgSocketAddrRequest_CALLBACK NULL
#define MsgSocketAddrRequest_DEFAULT NULL

#define MsgSocketAddrResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  addressLocal,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  addressRemote,     2) \
X(a, STATIC,   REQUIRED, INT32,    err,               3)
#define MsgSocketAddrResponse_CALLBACK NULL
#define MsgSocketAddrResponse_DEFAULT NULL
#define MsgSocketAddrResponse_addressLocal_MSGTYPE Address
#define MsgSocketAddrResponse_addressRemote_MSGTYPE Address

#define MsgSocketSendRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, CALLBACK, REQUIRED, BYTES,    data,              2) \
X(a, STATIC,   REQUIRED, UINT32,   flags,             3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  address,           4) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           5)
#define MsgSocketSendRequest_CALLBACK pb_default_field_callback
#define MsgSocketSendRequest_DEFAULT NULL
#define MsgSocketSendRequest_address_MSGTYPE Address

#define MsgSocketSendResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1) \
X(a, STATIC,   REQUIRED, INT32,    bytesSent,         2)
#define MsgSocketSendResponse_CALLBACK NULL
#define MsgSocketSendResponse_DEFAULT NULL

#define MsgSocketReceiveRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, UINT32,   flags,             2) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           3) \
X(a, STATIC,   REQUIRED, UINT32,   maxLen,            4) \
X(a, STATIC,   REQUIRED, BOOL,     addressRequested,   5)
#define MsgSocketReceiveRequest_CALLBACK NULL
#define MsgSocketReceiveRequest_DEFAULT NULL

#define MsgSocketReceiveResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1) \
X(a, CALLBACK, REQUIRED, BYTES,    data,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  address,           3)
#define MsgSocketReceiveResponse_CALLBACK pb_default_field_callback
#define MsgSocketReceiveResponse_DEFAULT NULL
#define MsgSocketReceiveResponse_address_MSGTYPE Address

#define MsgSocketCloseRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           4)
#define MsgSocketCloseRequest_CALLBACK NULL
#define MsgSocketCloseRequest_DEFAULT NULL

#define MsgSocketCloseResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1)
#define MsgSocketCloseResponse_CALLBACK NULL
#define MsgSocketCloseResponse_DEFAULT NULL

#define MsgGetHostByNameRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1)
#define MsgGetHostByNameRequest_CALLBACK NULL
#define MsgGetHostByNameRequest_DEFAULT NULL

#define MsgGetHostByNameResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, STRING,   alias,             2) \
X(a, STATIC,   REPEATED, UINT32,   addresses,         3) \
X(a, STATIC,   REQUIRED, INT32,    err,               4)
#define MsgGetHostByNameResponse_CALLBACK NULL
#define MsgGetHostByNameResponse_DEFAULT NULL

#define MsgGetServByNameRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, STRING,   protocol,          2)
#define MsgGetServByNameRequest_CALLBACK NULL
#define MsgGetServByNameRequest_DEFAULT NULL

#define MsgGetServByNameResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   port,              1) \
X(a, STATIC,   REQUIRED, INT32,    err,               2)
#define MsgGetServByNameResponse_CALLBACK NULL
#define MsgGetServByNameResponse_DEFAULT NULL

#define MsgSocketConnectRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, MESSAGE,  address,           2) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           3)
#define MsgSocketConnectRequest_CALLBACK NULL
#define MsgSocketConnectRequest_DEFAULT NULL
#define MsgSocketConnectRequest_address_MSGTYPE Address

#define MsgSocketConnectResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1)
#define MsgSocketConnectResponse_CALLBACK NULL
#define MsgSocketConnectResponse_DEFAULT NULL

#define MsgSelectRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   width,             2) \
X(a, STATIC,   REQUIRED, UINT32,   readFDs,           3) \
X(a, STATIC,   REQUIRED, UINT32,   writeFDs,          4) \
X(a, STATIC,   REQUIRED, UINT32,   exceptFDs,         5) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           6)
#define MsgSelectRequest_CALLBACK NULL
#define MsgSelectRequest_DEFAULT NULL

#define MsgSelectResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   readFDs,           1) \
X(a, STATIC,   REQUIRED, UINT32,   writeFDs,          2) \
X(a, STATIC,   REQUIRED, UINT32,   exceptFDs,         3) \
X(a, STATIC,   REQUIRED, INT32,    err,               4)
#define MsgSelectResponse_CALLBACK NULL
#define MsgSelectResponse_DEFAULT NULL

#define MsgInvalidRequestResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     tag,               1)
#define MsgInvalidRequestResponse_CALLBACK NULL
#define MsgInvalidRequestResponse_DEFAULT NULL

#define MsgSettingGetRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   setting,           1)
#define MsgSettingGetRequest_CALLBACK NULL
#define MsgSettingGetRequest_DEFAULT NULL

#define MsgSettingGetResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UINT32,   (value,uint32val,value.uint32val),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (value,uint8val,value.uint8val),   2) \
X(a, STATIC,   ONEOF,    STRING,   (value,strval,value.strval),   3) \
X(a, STATIC,   REQUIRED, INT32,    err,               4)
#define MsgSettingGetResponse_CALLBACK NULL
#define MsgSettingGetResponse_DEFAULT NULL

#define MsgSocketOptionSetRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, UINT32,   level,             2) \
X(a, STATIC,   REQUIRED, UINT32,   option,            3) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           4) \
X(a, STATIC,   ONEOF,    INT32,    (value,intval,value.intval),   6) \
X(a, STATIC,   ONEOF,    BYTES,    (value,bufval,value.bufval),   7)
#define MsgSocketOptionSetRequest_CALLBACK NULL
#define MsgSocketOptionSetRequest_DEFAULT NULL

#define MsgSocketOptionSetResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1)
#define MsgSocketOptionSetResponse_CALLBACK NULL
#define MsgSocketOptionSetResponse_DEFAULT NULL

#define MsgSocketOptionGetRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, UINT32,   level,             2) \
X(a, STATIC,   REQUIRED, UINT32,   option,            3) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           4)
#define MsgSocketOptionGetRequest_CALLBACK NULL
#define MsgSocketOptionGetRequest_DEFAULT NULL

#define MsgSocketOptionGetResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1) \
X(a, STATIC,   ONEOF,    INT32,    (value,intval,value.intval),   3) \
X(a, STATIC,   ONEOF,    BYTES,    (value,bufval,value.bufval),   4)
#define MsgSocketOptionGetResponse_CALLBACK NULL
#define MsgSocketOptionGetResponse_DEFAULT NULL

#define MsgSocketListenRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, INT32,    backlog,           2) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           3)
#define MsgSocketListenRequest_CALLBACK NULL
#define MsgSocketListenRequest_DEFAULT NULL

#define MsgSocketListenResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1)
#define MsgSocketListenResponse_CALLBACK NULL
#define MsgSocketListenResponse_DEFAULT NULL

#define MsgSocketAcceptRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           2)
#define MsgSocketAcceptRequest_CALLBACK NULL
#define MsgSocketAcceptRequest_DEFAULT NULL

#define MsgSocketAcceptResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, MESSAGE,  address,           2) \
X(a, STATIC,   REQUIRED, INT32,    err,               3)
#define MsgSocketAcceptResponse_CALLBACK NULL
#define MsgSocketAcceptResponse_DEFAULT NULL
#define MsgSocketAcceptResponse_address_MSGTYPE Address

#define MsgSocketShutdownRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    handle,            1) \
X(a, STATIC,   REQUIRED, INT32,    direction,         2) \
X(a, STATIC,   REQUIRED, INT32,    timeout,           3)
#define MsgSocketShutdownRequest_CALLBACK NULL
#define MsgSocketShutdownRequest_DEFAULT NULL

#define MsgSocketShutdownResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    err,               1)
#define MsgSocketShutdownResponse_CALLBACK NULL
#define MsgSocketShutdownResponse_DEFAULT NULL

#define MsgRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketOpenRequest,payload.socketOpenRequest),   2) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketBindRequest,payload.socketBindRequest),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketAddrRequest,payload.socketAddrRequest),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketSendRequest,payload.socketSendRequest),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketReceiveRequest,payload.socketReceiveRequest),   6) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketCloseRequest,payload.socketCloseRequest),   7) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,getHostByNameRequest,payload.getHostByNameRequest),   8) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,getServByNameRequest,payload.getServByNameRequest),   9) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketConnectRequest,payload.socketConnectRequest),  10) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,selectRequest,payload.selectRequest),  11) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,settingGetRequest,payload.settingGetRequest),  12) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketOptionSetRequest,payload.socketOptionSetRequest),  13) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketListenRequest,payload.socketListenRequest),  14) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketAcceptRequest,payload.socketAcceptRequest),  15) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketOptionGetRequest,payload.socketOptionGetRequest),  16) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketShutdownRequest,payload.socketShutdownRequest),  17)
#define MsgRequest_CALLBACK NULL
#define MsgRequest_DEFAULT NULL
#define MsgRequest_payload_socketOpenRequest_MSGTYPE MsgSocketOpenRequest
#define MsgRequest_payload_socketBindRequest_MSGTYPE MsgSocketBindRequest
#define MsgRequest_payload_socketAddrRequest_MSGTYPE MsgSocketAddrRequest
#define MsgRequest_payload_socketSendRequest_MSGTYPE MsgSocketSendRequest
#define MsgRequest_payload_socketReceiveRequest_MSGTYPE MsgSocketReceiveRequest
#define MsgRequest_payload_socketCloseRequest_MSGTYPE MsgSocketCloseRequest
#define MsgRequest_payload_getHostByNameRequest_MSGTYPE MsgGetHostByNameRequest
#define MsgRequest_payload_getServByNameRequest_MSGTYPE MsgGetServByNameRequest
#define MsgRequest_payload_socketConnectRequest_MSGTYPE MsgSocketConnectRequest
#define MsgRequest_payload_selectRequest_MSGTYPE MsgSelectRequest
#define MsgRequest_payload_settingGetRequest_MSGTYPE MsgSettingGetRequest
#define MsgRequest_payload_socketOptionSetRequest_MSGTYPE MsgSocketOptionSetRequest
#define MsgRequest_payload_socketListenRequest_MSGTYPE MsgSocketListenRequest
#define MsgRequest_payload_socketAcceptRequest_MSGTYPE MsgSocketAcceptRequest
#define MsgRequest_payload_socketOptionGetRequest_MSGTYPE MsgSocketOptionGetRequest
#define MsgRequest_payload_socketShutdownRequest_MSGTYPE MsgSocketShutdownRequest

#define MsgResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketOpenResponse,payload.socketOpenResponse),   2) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketBindResponse,payload.socketBindResponse),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketAddrResponse,payload.socketAddrResponse),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketSendResponse,payload.socketSendResponse),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketReceiveResponse,payload.socketReceiveResponse),   6) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketCloseResponse,payload.socketCloseResponse),   7) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,getHostByNameResponse,payload.getHostByNameResponse),   8) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,getServByNameResponse,payload.getServByNameResponse),   9) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketConnectResponse,payload.socketConnectResponse),  10) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,selectResponse,payload.selectResponse),  11) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,settingGetResponse,payload.settingGetResponse),  12) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketOptionSetResponse,payload.socketOptionSetResponse),  13) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketListenResponse,payload.socketListenResponse),  14) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketAcceptResponse,payload.socketAcceptResponse),  15) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketOptionGetResponse,payload.socketOptionGetResponse),  16) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,socketShutdownResponse,payload.socketShutdownResponse),  17) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,invalidRequestResponse,payload.invalidRequestResponse), 255)
#define MsgResponse_CALLBACK NULL
#define MsgResponse_DEFAULT NULL
#define MsgResponse_payload_socketOpenResponse_MSGTYPE MsgSocketOpenResponse
#define MsgResponse_payload_socketBindResponse_MSGTYPE MsgSocketBindResponse
#define MsgResponse_payload_socketAddrResponse_MSGTYPE MsgSocketAddrResponse
#define MsgResponse_payload_socketSendResponse_MSGTYPE MsgSocketSendResponse
#define MsgResponse_payload_socketReceiveResponse_MSGTYPE MsgSocketReceiveResponse
#define MsgResponse_payload_socketCloseResponse_MSGTYPE MsgSocketCloseResponse
#define MsgResponse_payload_getHostByNameResponse_MSGTYPE MsgGetHostByNameResponse
#define MsgResponse_payload_getServByNameResponse_MSGTYPE MsgGetServByNameResponse
#define MsgResponse_payload_socketConnectResponse_MSGTYPE MsgSocketConnectResponse
#define MsgResponse_payload_selectResponse_MSGTYPE MsgSelectResponse
#define MsgResponse_payload_settingGetResponse_MSGTYPE MsgSettingGetResponse
#define MsgResponse_payload_socketOptionSetResponse_MSGTYPE MsgSocketOptionSetResponse
#define MsgResponse_payload_socketListenResponse_MSGTYPE MsgSocketListenResponse
#define MsgResponse_payload_socketAcceptResponse_MSGTYPE MsgSocketAcceptResponse
#define MsgResponse_payload_socketOptionGetResponse_MSGTYPE MsgSocketOptionGetResponse
#define MsgResponse_payload_socketShutdownResponse_MSGTYPE MsgSocketShutdownResponse
#define MsgResponse_payload_invalidRequestResponse_MSGTYPE MsgInvalidRequestResponse

extern const pb_msgdesc_t Address_msg;
extern const pb_msgdesc_t MsgSocketOpenRequest_msg;
extern const pb_msgdesc_t MsgSocketOpenResponse_msg;
extern const pb_msgdesc_t MsgSocketBindRequest_msg;
extern const pb_msgdesc_t MsgSocketBindResponse_msg;
extern const pb_msgdesc_t MsgSocketAddrRequest_msg;
extern const pb_msgdesc_t MsgSocketAddrResponse_msg;
extern const pb_msgdesc_t MsgSocketSendRequest_msg;
extern const pb_msgdesc_t MsgSocketSendResponse_msg;
extern const pb_msgdesc_t MsgSocketReceiveRequest_msg;
extern const pb_msgdesc_t MsgSocketReceiveResponse_msg;
extern const pb_msgdesc_t MsgSocketCloseRequest_msg;
extern const pb_msgdesc_t MsgSocketCloseResponse_msg;
extern const pb_msgdesc_t MsgGetHostByNameRequest_msg;
extern const pb_msgdesc_t MsgGetHostByNameResponse_msg;
extern const pb_msgdesc_t MsgGetServByNameRequest_msg;
extern const pb_msgdesc_t MsgGetServByNameResponse_msg;
extern const pb_msgdesc_t MsgSocketConnectRequest_msg;
extern const pb_msgdesc_t MsgSocketConnectResponse_msg;
extern const pb_msgdesc_t MsgSelectRequest_msg;
extern const pb_msgdesc_t MsgSelectResponse_msg;
extern const pb_msgdesc_t MsgInvalidRequestResponse_msg;
extern const pb_msgdesc_t MsgSettingGetRequest_msg;
extern const pb_msgdesc_t MsgSettingGetResponse_msg;
extern const pb_msgdesc_t MsgSocketOptionSetRequest_msg;
extern const pb_msgdesc_t MsgSocketOptionSetResponse_msg;
extern const pb_msgdesc_t MsgSocketOptionGetRequest_msg;
extern const pb_msgdesc_t MsgSocketOptionGetResponse_msg;
extern const pb_msgdesc_t MsgSocketListenRequest_msg;
extern const pb_msgdesc_t MsgSocketListenResponse_msg;
extern const pb_msgdesc_t MsgSocketAcceptRequest_msg;
extern const pb_msgdesc_t MsgSocketAcceptResponse_msg;
extern const pb_msgdesc_t MsgSocketShutdownRequest_msg;
extern const pb_msgdesc_t MsgSocketShutdownResponse_msg;
extern const pb_msgdesc_t MsgRequest_msg;
extern const pb_msgdesc_t MsgResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Address_fields &Address_msg
#define MsgSocketOpenRequest_fields &MsgSocketOpenRequest_msg
#define MsgSocketOpenResponse_fields &MsgSocketOpenResponse_msg
#define MsgSocketBindRequest_fields &MsgSocketBindRequest_msg
#define MsgSocketBindResponse_fields &MsgSocketBindResponse_msg
#define MsgSocketAddrRequest_fields &MsgSocketAddrRequest_msg
#define MsgSocketAddrResponse_fields &MsgSocketAddrResponse_msg
#define MsgSocketSendRequest_fields &MsgSocketSendRequest_msg
#define MsgSocketSendResponse_fields &MsgSocketSendResponse_msg
#define MsgSocketReceiveRequest_fields &MsgSocketReceiveRequest_msg
#define MsgSocketReceiveResponse_fields &MsgSocketReceiveResponse_msg
#define MsgSocketCloseRequest_fields &MsgSocketCloseRequest_msg
#define MsgSocketCloseResponse_fields &MsgSocketCloseResponse_msg
#define MsgGetHostByNameRequest_fields &MsgGetHostByNameRequest_msg
#define MsgGetHostByNameResponse_fields &MsgGetHostByNameResponse_msg
#define MsgGetServByNameRequest_fields &MsgGetServByNameRequest_msg
#define MsgGetServByNameResponse_fields &MsgGetServByNameResponse_msg
#define MsgSocketConnectRequest_fields &MsgSocketConnectRequest_msg
#define MsgSocketConnectResponse_fields &MsgSocketConnectResponse_msg
#define MsgSelectRequest_fields &MsgSelectRequest_msg
#define MsgSelectResponse_fields &MsgSelectResponse_msg
#define MsgInvalidRequestResponse_fields &MsgInvalidRequestResponse_msg
#define MsgSettingGetRequest_fields &MsgSettingGetRequest_msg
#define MsgSettingGetResponse_fields &MsgSettingGetResponse_msg
#define MsgSocketOptionSetRequest_fields &MsgSocketOptionSetRequest_msg
#define MsgSocketOptionSetResponse_fields &MsgSocketOptionSetResponse_msg
#define MsgSocketOptionGetRequest_fields &MsgSocketOptionGetRequest_msg
#define MsgSocketOptionGetResponse_fields &MsgSocketOptionGetResponse_msg
#define MsgSocketListenRequest_fields &MsgSocketListenRequest_msg
#define MsgSocketListenResponse_fields &MsgSocketListenResponse_msg
#define MsgSocketAcceptRequest_fields &MsgSocketAcceptRequest_msg
#define MsgSocketAcceptResponse_fields &MsgSocketAcceptResponse_msg
#define MsgSocketShutdownRequest_fields &MsgSocketShutdownRequest_msg
#define MsgSocketShutdownResponse_fields &MsgSocketShutdownResponse_msg
#define MsgRequest_fields &MsgRequest_msg
#define MsgResponse_fields &MsgResponse_msg

/* Maximum encoded size of messages (where known) */
/* MsgSocketSendRequest_size depends on runtime parameters */
/* MsgSocketReceiveResponse_size depends on runtime parameters */
/* MsgRequest_size depends on runtime parameters */
/* MsgResponse_size depends on runtime parameters */
#define Address_size                             17
#define MsgGetHostByNameRequest_size             258
#define MsgGetHostByNameResponse_size            545
#define MsgGetServByNameRequest_size             22
#define MsgGetServByNameResponse_size            17
#define MsgInvalidRequestResponse_size           2
#define MsgSelectRequest_size                    35
#define MsgSelectResponse_size                   29
#define MsgSettingGetRequest_size                6
#define MsgSettingGetResponse_size               269
#define MsgSocketAcceptRequest_size              22
#define MsgSocketAcceptResponse_size             41
#define MsgSocketAddrRequest_size                26
#define MsgSocketAddrResponse_size               49
#define MsgSocketBindRequest_size                41
#define MsgSocketBindResponse_size               11
#define MsgSocketCloseRequest_size               22
#define MsgSocketCloseResponse_size              11
#define MsgSocketConnectRequest_size             41
#define MsgSocketConnectResponse_size            11
#define MsgSocketListenRequest_size              33
#define MsgSocketListenResponse_size             11
#define MsgSocketOpenRequest_size                12
#define MsgSocketOpenResponse_size               22
#define MsgSocketOptionGetRequest_size           34
#define MsgSocketOptionGetResponse_size          53
#define MsgSocketOptionSetRequest_size           76
#define MsgSocketOptionSetResponse_size          11
#define MsgSocketReceiveRequest_size             36
#define MsgSocketSendResponse_size               22
#define MsgSocketShutdownRequest_size            33
#define MsgSocketShutdownResponse_size           11
#define NETWORKING_PB_H_MAX_SIZE                 MsgGetHostByNameResponse_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
