interface Cloudpilot {
    void Cloudpilot();

    VoidPtr Malloc(long size);
    void Free(VoidPtr buffer);

    boolean GetRomInfo(VoidPtr buffer, long size, [Ref] RomInfo romInfo);
};

interface RomInfo {
    void RomInfo();

    long CardVersion();
    [Const] DOMString CardName();
    long RomVersion();
    [Const] DOMString RomVersionString();
};
