/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "networking.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MsgSocketOpenRequest, MsgSocketOpenRequest, AUTO)


PB_BIND(MsgSocketOpenResponse, MsgSocketOpenResponse, AUTO)


PB_BIND(MsgRequest, MsgRequest, AUTO)


PB_BIND(MsgResponse, MsgResponse, AUTO)



