/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "networking.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Address, Address, AUTO)


PB_BIND(MsgSocketOpenRequest, MsgSocketOpenRequest, AUTO)


PB_BIND(MsgSocketOpenResponse, MsgSocketOpenResponse, AUTO)


PB_BIND(MsgSocketBindRequest, MsgSocketBindRequest, AUTO)


PB_BIND(MsgSocketBindResponse, MsgSocketBindResponse, AUTO)


PB_BIND(MsgSocketAddrRequest, MsgSocketAddrRequest, AUTO)


PB_BIND(MsgSocketAddrResponse, MsgSocketAddrResponse, AUTO)


PB_BIND(MsgSocketSendRequest, MsgSocketSendRequest, AUTO)


PB_BIND(MsgSocketSendResponse, MsgSocketSendResponse, AUTO)


PB_BIND(MsgSocketReceiveRequest, MsgSocketReceiveRequest, AUTO)


PB_BIND(MsgSocketReceiveResponse, MsgSocketReceiveResponse, AUTO)


PB_BIND(MsgSocketCloseRequest, MsgSocketCloseRequest, AUTO)


PB_BIND(MsgSocketCloseResponse, MsgSocketCloseResponse, AUTO)


PB_BIND(MsgRequest, MsgRequest, AUTO)


PB_BIND(MsgResponse, MsgResponse, AUTO)



