#ifndef _FRAME_H_
#define _FRAME_H_

#include <memory>

#include "EmCommon.h"

struct Frame {
    Frame(size_t bufferSize);

    uint8 bpp{0};

    uint32 lineWidth{0};
    uint32 lines{0};
    uint8 margin{0};
    uint32 bytesPerLine{0};

    bool hasChanges{true};
    uint32 firstDirtyLine{0};
    uint32 lastDirtyLine{0};

    uint8* GetBuffer();
    size_t GetBufferSize() const;

    // using getters in the autogenerated IDL wrapper causes Safari to crash on iOS,
    // so add a bunch of accessors here.
    uint8 GetBpp() const;
    uint32 GetLineWidth() const;
    uint32 GetLines() const;
    uint8 GetMargin() const;
    uint32 GetBytesPerLine() const;

    uint32 GetFirstDirtyLine() const;
    uint32 GetLastDirtyLine() const;
    bool GetHasChanges() const;

   private:
    const unique_ptr<uint8[]> buffer;
    const size_t bufferSize;

    Frame(const Frame&) = delete;
    Frame(Frame&&) = delete;

    Frame& operator=(const Frame&) = delete;
    Frame& operator=(Frame&&) = delete;
};

#endif  // _FRAME_H_
