interface FileEntry {
    [Const] DOMString GetName();
    boolean IsDirectory();
    long GetSize();
    long GetModifiedTS();
    long GetAttributes();
};

interface Vfs {
    void Vfs();

    VoidPtr Malloc(long size);
    void Free(VoidPtr buffer);
    VoidPtr Nullptr();

    void AllocateImage(long blockCount);
    boolean MountImage(long slot);
    void UnmountImage(long slot);

    long GetPendingImageSize();
    long GetSize(long slot);
    VoidPtr GetPendingImage();
    VoidPtr GetImage(long slot);
    VoidPtr GetDirtyPages(long slot);

    long RenameFile([Const] DOMString from, [Const] DOMString to);
    long ChmodFile([Const] DOMString path, long attr, long mask);
    long StatFile([Const] DOMString path);

    [Const, Ref] FileEntry GetEntry();

    long BytesFree(long slot);
    long BytesTotal(long slot);

    boolean ReadFile([Const] DOMString path);
    long GetCurrentFileSize();
    VoidPtr GetCurrentFileContent();
    void ReleaseCurrentFile();
};

interface ReaddirContext {
    void ReaddirContext([Const] DOMString path);

    long Next();

    [Const,Ref] FileEntry GetEntry();

    long GetStatus();
    long GetError();
    [Const] DOMString GetErrorDescription();
};

interface CreateZipContext {
    void CreateZipContext([Const] DOMString path);

    [Ref] CreateZipContext AddFile([Const] DOMString path);
    [Ref] CreateZipContext AddDirectory([Const] DOMString path);

    long Continue();
    long GetState();

    VoidPtr GetZipContent();
    long GetZipSize();

    [Const] DOMString GetErrorItem();
};
