interface Vfs {
    void Vfs();

    VoidPtr Malloc(long size);
    void Free(VoidPtr buffer);
    VoidPtr Nullptr();

    void AllocateImage(long blockCount);
    boolean MountImage(long slot);
    void UnmountImage(long slot);

    long GetPendingImageSize();
    long GetSize(long slot);
    VoidPtr GetPendingImage();
    VoidPtr GetImage(long slot);
};

interface ReaddirContext {
    void ReaddirContext([Const] DOMString path);

    long Next();

    [Const] DOMString GetEntryName();

    boolean IsEntryDirectory();
    long GetEntrySize();
    long GetEntryModifiedTS();

    long GetStatus();
    long GetError();
    [Const] DOMString GetErrorDescription();
};
