interface RomInfo5 {
    void RomInfo5([Const] VoidPtr data, long size);

    boolean IsValid();

    [Const] DOMString GetCardName();
    [Const] DOMString GetManufacturer();
    [Const] DOMString GetRomName();

    long GetCompanyId();
    long GetHalId();
    boolean NeedsNand();

    long GetDeviceType();

    long GetRecommendedRamSize();
};