"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Address(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    ip: builtins.int
    port: builtins.int
    def __init__(
        self,
        *,
        ip: builtins.int | None = ...,
        port: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ip", b"ip", "port", b"port"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ip", b"ip", "port", b"port"]) -> None: ...

global___Address = Address

@typing.final
class MsgSocketOpenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    type: builtins.int
    protocol: builtins.int
    def __init__(
        self,
        *,
        type: builtins.int | None = ...,
        protocol: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["protocol", b"protocol", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["protocol", b"protocol", "type", b"type"]) -> None: ...

global___MsgSocketOpenRequest = MsgSocketOpenRequest

@typing.final
class MsgSocketOpenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    handle: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err", "handle", b"handle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err", "handle", b"handle"]) -> None: ...

global___MsgSocketOpenResponse = MsgSocketOpenResponse

@typing.final
class MsgSocketBindRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    timeout: builtins.int
    @property
    def address(self) -> global___Address: ...
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        address: global___Address | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address", "handle", b"handle", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "handle", b"handle", "timeout", b"timeout"]) -> None: ...

global___MsgSocketBindRequest = MsgSocketBindRequest

@typing.final
class MsgSocketBindResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err"]) -> None: ...

global___MsgSocketBindResponse = MsgSocketBindResponse

@typing.final
class MsgSocketAddrRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    REQUESTADDRESSLOCAL_FIELD_NUMBER: builtins.int
    REQUESTADDRESSREMOTE_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    requestAddressLocal: builtins.bool
    requestAddressRemote: builtins.bool
    timeout: builtins.int
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        requestAddressLocal: builtins.bool | None = ...,
        requestAddressRemote: builtins.bool | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["handle", b"handle", "requestAddressLocal", b"requestAddressLocal", "requestAddressRemote", b"requestAddressRemote", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["handle", b"handle", "requestAddressLocal", b"requestAddressLocal", "requestAddressRemote", b"requestAddressRemote", "timeout", b"timeout"]) -> None: ...

global___MsgSocketAddrRequest = MsgSocketAddrRequest

@typing.final
class MsgSocketAddrResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESSLOCAL_FIELD_NUMBER: builtins.int
    ADDRESSREMOTE_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    err: builtins.int
    @property
    def addressLocal(self) -> global___Address: ...
    @property
    def addressRemote(self) -> global___Address: ...
    def __init__(
        self,
        *,
        addressLocal: global___Address | None = ...,
        addressRemote: global___Address | None = ...,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["addressLocal", b"addressLocal", "addressRemote", b"addressRemote", "err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["addressLocal", b"addressLocal", "addressRemote", b"addressRemote", "err", b"err"]) -> None: ...

global___MsgSocketAddrResponse = MsgSocketAddrResponse

@typing.final
class MsgSocketSendRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    data: builtins.bytes
    flags: builtins.int
    timeout: builtins.int
    @property
    def address(self) -> global___Address: ...
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        data: builtins.bytes | None = ...,
        flags: builtins.int | None = ...,
        address: global___Address | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address", "data", b"data", "flags", b"flags", "handle", b"handle", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "data", b"data", "flags", b"flags", "handle", b"handle", "timeout", b"timeout"]) -> None: ...

global___MsgSocketSendRequest = MsgSocketSendRequest

@typing.final
class MsgSocketSendResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    BYTESSENT_FIELD_NUMBER: builtins.int
    err: builtins.int
    bytesSent: builtins.int
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
        bytesSent: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bytesSent", b"bytesSent", "err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bytesSent", b"bytesSent", "err", b"err"]) -> None: ...

global___MsgSocketSendResponse = MsgSocketSendResponse

@typing.final
class MsgSocketReceiveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    MAXLEN_FIELD_NUMBER: builtins.int
    ADDRESSREQUESTED_FIELD_NUMBER: builtins.int
    handle: builtins.int
    flags: builtins.int
    timeout: builtins.int
    maxLen: builtins.int
    addressRequested: builtins.bool
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        flags: builtins.int | None = ...,
        timeout: builtins.int | None = ...,
        maxLen: builtins.int | None = ...,
        addressRequested: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["addressRequested", b"addressRequested", "flags", b"flags", "handle", b"handle", "maxLen", b"maxLen", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["addressRequested", b"addressRequested", "flags", b"flags", "handle", b"handle", "maxLen", b"maxLen", "timeout", b"timeout"]) -> None: ...

global___MsgSocketReceiveRequest = MsgSocketReceiveRequest

@typing.final
class MsgSocketReceiveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    err: builtins.int
    data: builtins.bytes
    @property
    def address(self) -> global___Address: ...
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
        data: builtins.bytes | None = ...,
        address: global___Address | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address", "data", b"data", "err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "data", b"data", "err", b"err"]) -> None: ...

global___MsgSocketReceiveResponse = MsgSocketReceiveResponse

@typing.final
class MsgSocketCloseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    timeout: builtins.int
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["handle", b"handle", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["handle", b"handle", "timeout", b"timeout"]) -> None: ...

global___MsgSocketCloseRequest = MsgSocketCloseRequest

@typing.final
class MsgSocketCloseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err"]) -> None: ...

global___MsgSocketCloseResponse = MsgSocketCloseResponse

@typing.final
class MsgGetHostByNameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___MsgGetHostByNameRequest = MsgGetHostByNameRequest

@typing.final
class MsgGetHostByNameResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    ADDRESSES_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    name: builtins.str
    alias: builtins.str
    err: builtins.int
    @property
    def addresses(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        alias: builtins.str | None = ...,
        addresses: collections.abc.Iterable[builtins.int] | None = ...,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["alias", b"alias", "err", b"err", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["addresses", b"addresses", "alias", b"alias", "err", b"err", "name", b"name"]) -> None: ...

global___MsgGetHostByNameResponse = MsgGetHostByNameResponse

@typing.final
class MsgGetServByNameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    name: builtins.str
    protocol: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        protocol: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["name", b"name", "protocol", b"protocol"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "protocol", b"protocol"]) -> None: ...

global___MsgGetServByNameRequest = MsgGetServByNameRequest

@typing.final
class MsgGetServByNameResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PORT_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    port: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        port: builtins.int | None = ...,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err", "port", b"port"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err", "port", b"port"]) -> None: ...

global___MsgGetServByNameResponse = MsgGetServByNameResponse

@typing.final
class MsgSocketConnectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    timeout: builtins.int
    @property
    def address(self) -> global___Address: ...
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        address: global___Address | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address", "handle", b"handle", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "handle", b"handle", "timeout", b"timeout"]) -> None: ...

global___MsgSocketConnectRequest = MsgSocketConnectRequest

@typing.final
class MsgSocketConnectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err"]) -> None: ...

global___MsgSocketConnectResponse = MsgSocketConnectResponse

@typing.final
class MsgSelectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    READFDS_FIELD_NUMBER: builtins.int
    WRITEFDS_FIELD_NUMBER: builtins.int
    EXCEPTFDS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    width: builtins.int
    readFDs: builtins.int
    writeFDs: builtins.int
    exceptFDs: builtins.int
    timeout: builtins.int
    def __init__(
        self,
        *,
        width: builtins.int | None = ...,
        readFDs: builtins.int | None = ...,
        writeFDs: builtins.int | None = ...,
        exceptFDs: builtins.int | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["exceptFDs", b"exceptFDs", "readFDs", b"readFDs", "timeout", b"timeout", "width", b"width", "writeFDs", b"writeFDs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["exceptFDs", b"exceptFDs", "readFDs", b"readFDs", "timeout", b"timeout", "width", b"width", "writeFDs", b"writeFDs"]) -> None: ...

global___MsgSelectRequest = MsgSelectRequest

@typing.final
class MsgSelectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    READFDS_FIELD_NUMBER: builtins.int
    WRITEFDS_FIELD_NUMBER: builtins.int
    EXCEPTFDS_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    readFDs: builtins.int
    writeFDs: builtins.int
    exceptFDs: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        readFDs: builtins.int | None = ...,
        writeFDs: builtins.int | None = ...,
        exceptFDs: builtins.int | None = ...,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err", "exceptFDs", b"exceptFDs", "readFDs", b"readFDs", "writeFDs", b"writeFDs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err", "exceptFDs", b"exceptFDs", "readFDs", b"readFDs", "writeFDs", b"writeFDs"]) -> None: ...

global___MsgSelectResponse = MsgSelectResponse

@typing.final
class MsgInvalidRequestResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    tag: builtins.bool
    def __init__(
        self,
        *,
        tag: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tag", b"tag"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["tag", b"tag"]) -> None: ...

global___MsgInvalidRequestResponse = MsgInvalidRequestResponse

@typing.final
class MsgSettingGetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SETTING_FIELD_NUMBER: builtins.int
    setting: builtins.int
    def __init__(
        self,
        *,
        setting: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["setting", b"setting"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["setting", b"setting"]) -> None: ...

global___MsgSettingGetRequest = MsgSettingGetRequest

@typing.final
class MsgSettingGetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UINT32VAL_FIELD_NUMBER: builtins.int
    UINT8VAL_FIELD_NUMBER: builtins.int
    STRVAL_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    uint32val: builtins.int
    uint8val: builtins.int
    strval: builtins.str
    err: builtins.int
    def __init__(
        self,
        *,
        uint32val: builtins.int | None = ...,
        uint8val: builtins.int | None = ...,
        strval: builtins.str | None = ...,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err", "strval", b"strval", "uint32val", b"uint32val", "uint8val", b"uint8val", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err", "strval", b"strval", "uint32val", b"uint32val", "uint8val", b"uint8val", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["uint32val", "uint8val", "strval"] | None: ...

global___MsgSettingGetResponse = MsgSettingGetResponse

@typing.final
class MsgSocketOptionSetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    OPTION_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    INTVAL_FIELD_NUMBER: builtins.int
    BUFVAL_FIELD_NUMBER: builtins.int
    handle: builtins.int
    level: builtins.int
    option: builtins.int
    timeout: builtins.int
    intval: builtins.int
    bufval: builtins.bytes
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        level: builtins.int | None = ...,
        option: builtins.int | None = ...,
        timeout: builtins.int | None = ...,
        intval: builtins.int | None = ...,
        bufval: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bufval", b"bufval", "handle", b"handle", "intval", b"intval", "level", b"level", "option", b"option", "timeout", b"timeout", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bufval", b"bufval", "handle", b"handle", "intval", b"intval", "level", b"level", "option", b"option", "timeout", b"timeout", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["intval", "bufval"] | None: ...

global___MsgSocketOptionSetRequest = MsgSocketOptionSetRequest

@typing.final
class MsgSocketOptionSetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err"]) -> None: ...

global___MsgSocketOptionSetResponse = MsgSocketOptionSetResponse

@typing.final
class MsgSocketOptionGetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    OPTION_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    level: builtins.int
    option: builtins.int
    timeout: builtins.int
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        level: builtins.int | None = ...,
        option: builtins.int | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["handle", b"handle", "level", b"level", "option", b"option", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["handle", b"handle", "level", b"level", "option", b"option", "timeout", b"timeout"]) -> None: ...

global___MsgSocketOptionGetRequest = MsgSocketOptionGetRequest

@typing.final
class MsgSocketOptionGetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    INTVAL_FIELD_NUMBER: builtins.int
    BUFVAL_FIELD_NUMBER: builtins.int
    err: builtins.int
    intval: builtins.int
    bufval: builtins.bytes
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
        intval: builtins.int | None = ...,
        bufval: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bufval", b"bufval", "err", b"err", "intval", b"intval", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bufval", b"bufval", "err", b"err", "intval", b"intval", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["intval", "bufval"] | None: ...

global___MsgSocketOptionGetResponse = MsgSocketOptionGetResponse

@typing.final
class MsgSocketListenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    BACKLOG_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    backlog: builtins.int
    timeout: builtins.int
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        backlog: builtins.int | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["backlog", b"backlog", "handle", b"handle", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["backlog", b"backlog", "handle", b"handle", "timeout", b"timeout"]) -> None: ...

global___MsgSocketListenRequest = MsgSocketListenRequest

@typing.final
class MsgSocketListenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err"]) -> None: ...

global___MsgSocketListenResponse = MsgSocketListenResponse

@typing.final
class MsgSocketAcceptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    timeout: builtins.int
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["handle", b"handle", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["handle", b"handle", "timeout", b"timeout"]) -> None: ...

global___MsgSocketAcceptRequest = MsgSocketAcceptRequest

@typing.final
class MsgSocketAcceptResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    ERR_FIELD_NUMBER: builtins.int
    handle: builtins.int
    err: builtins.int
    @property
    def address(self) -> global___Address: ...
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        address: global___Address | None = ...,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["address", b"address", "err", b"err", "handle", b"handle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "err", b"err", "handle", b"handle"]) -> None: ...

global___MsgSocketAcceptResponse = MsgSocketAcceptResponse

@typing.final
class MsgSocketShutdownRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    handle: builtins.int
    direction: builtins.int
    timeout: builtins.int
    def __init__(
        self,
        *,
        handle: builtins.int | None = ...,
        direction: builtins.int | None = ...,
        timeout: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["direction", b"direction", "handle", b"handle", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["direction", b"direction", "handle", b"handle", "timeout", b"timeout"]) -> None: ...

global___MsgSocketShutdownRequest = MsgSocketShutdownRequest

@typing.final
class MsgSocketShutdownResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_FIELD_NUMBER: builtins.int
    err: builtins.int
    def __init__(
        self,
        *,
        err: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["err", b"err"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["err", b"err"]) -> None: ...

global___MsgSocketShutdownResponse = MsgSocketShutdownResponse

@typing.final
class MsgRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    SOCKETOPENREQUEST_FIELD_NUMBER: builtins.int
    SOCKETBINDREQUEST_FIELD_NUMBER: builtins.int
    SOCKETADDRREQUEST_FIELD_NUMBER: builtins.int
    SOCKETSENDREQUEST_FIELD_NUMBER: builtins.int
    SOCKETRECEIVEREQUEST_FIELD_NUMBER: builtins.int
    SOCKETCLOSEREQUEST_FIELD_NUMBER: builtins.int
    GETHOSTBYNAMEREQUEST_FIELD_NUMBER: builtins.int
    GETSERVBYNAMEREQUEST_FIELD_NUMBER: builtins.int
    SOCKETCONNECTREQUEST_FIELD_NUMBER: builtins.int
    SELECTREQUEST_FIELD_NUMBER: builtins.int
    SETTINGGETREQUEST_FIELD_NUMBER: builtins.int
    SOCKETOPTIONSETREQUEST_FIELD_NUMBER: builtins.int
    SOCKETLISTENREQUEST_FIELD_NUMBER: builtins.int
    SOCKETACCEPTREQUEST_FIELD_NUMBER: builtins.int
    SOCKETOPTIONGETREQUEST_FIELD_NUMBER: builtins.int
    SOCKETSHUTDOWNREQUEST_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def socketOpenRequest(self) -> global___MsgSocketOpenRequest: ...
    @property
    def socketBindRequest(self) -> global___MsgSocketBindRequest: ...
    @property
    def socketAddrRequest(self) -> global___MsgSocketAddrRequest: ...
    @property
    def socketSendRequest(self) -> global___MsgSocketSendRequest: ...
    @property
    def socketReceiveRequest(self) -> global___MsgSocketReceiveRequest: ...
    @property
    def socketCloseRequest(self) -> global___MsgSocketCloseRequest: ...
    @property
    def getHostByNameRequest(self) -> global___MsgGetHostByNameRequest: ...
    @property
    def getServByNameRequest(self) -> global___MsgGetServByNameRequest: ...
    @property
    def socketConnectRequest(self) -> global___MsgSocketConnectRequest: ...
    @property
    def selectRequest(self) -> global___MsgSelectRequest: ...
    @property
    def settingGetRequest(self) -> global___MsgSettingGetRequest: ...
    @property
    def socketOptionSetRequest(self) -> global___MsgSocketOptionSetRequest: ...
    @property
    def socketListenRequest(self) -> global___MsgSocketListenRequest: ...
    @property
    def socketAcceptRequest(self) -> global___MsgSocketAcceptRequest: ...
    @property
    def socketOptionGetRequest(self) -> global___MsgSocketOptionGetRequest: ...
    @property
    def socketShutdownRequest(self) -> global___MsgSocketShutdownRequest: ...
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        socketOpenRequest: global___MsgSocketOpenRequest | None = ...,
        socketBindRequest: global___MsgSocketBindRequest | None = ...,
        socketAddrRequest: global___MsgSocketAddrRequest | None = ...,
        socketSendRequest: global___MsgSocketSendRequest | None = ...,
        socketReceiveRequest: global___MsgSocketReceiveRequest | None = ...,
        socketCloseRequest: global___MsgSocketCloseRequest | None = ...,
        getHostByNameRequest: global___MsgGetHostByNameRequest | None = ...,
        getServByNameRequest: global___MsgGetServByNameRequest | None = ...,
        socketConnectRequest: global___MsgSocketConnectRequest | None = ...,
        selectRequest: global___MsgSelectRequest | None = ...,
        settingGetRequest: global___MsgSettingGetRequest | None = ...,
        socketOptionSetRequest: global___MsgSocketOptionSetRequest | None = ...,
        socketListenRequest: global___MsgSocketListenRequest | None = ...,
        socketAcceptRequest: global___MsgSocketAcceptRequest | None = ...,
        socketOptionGetRequest: global___MsgSocketOptionGetRequest | None = ...,
        socketShutdownRequest: global___MsgSocketShutdownRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["getHostByNameRequest", b"getHostByNameRequest", "getServByNameRequest", b"getServByNameRequest", "id", b"id", "payload", b"payload", "selectRequest", b"selectRequest", "settingGetRequest", b"settingGetRequest", "socketAcceptRequest", b"socketAcceptRequest", "socketAddrRequest", b"socketAddrRequest", "socketBindRequest", b"socketBindRequest", "socketCloseRequest", b"socketCloseRequest", "socketConnectRequest", b"socketConnectRequest", "socketListenRequest", b"socketListenRequest", "socketOpenRequest", b"socketOpenRequest", "socketOptionGetRequest", b"socketOptionGetRequest", "socketOptionSetRequest", b"socketOptionSetRequest", "socketReceiveRequest", b"socketReceiveRequest", "socketSendRequest", b"socketSendRequest", "socketShutdownRequest", b"socketShutdownRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["getHostByNameRequest", b"getHostByNameRequest", "getServByNameRequest", b"getServByNameRequest", "id", b"id", "payload", b"payload", "selectRequest", b"selectRequest", "settingGetRequest", b"settingGetRequest", "socketAcceptRequest", b"socketAcceptRequest", "socketAddrRequest", b"socketAddrRequest", "socketBindRequest", b"socketBindRequest", "socketCloseRequest", b"socketCloseRequest", "socketConnectRequest", b"socketConnectRequest", "socketListenRequest", b"socketListenRequest", "socketOpenRequest", b"socketOpenRequest", "socketOptionGetRequest", b"socketOptionGetRequest", "socketOptionSetRequest", b"socketOptionSetRequest", "socketReceiveRequest", b"socketReceiveRequest", "socketSendRequest", b"socketSendRequest", "socketShutdownRequest", b"socketShutdownRequest"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["socketOpenRequest", "socketBindRequest", "socketAddrRequest", "socketSendRequest", "socketReceiveRequest", "socketCloseRequest", "getHostByNameRequest", "getServByNameRequest", "socketConnectRequest", "selectRequest", "settingGetRequest", "socketOptionSetRequest", "socketListenRequest", "socketAcceptRequest", "socketOptionGetRequest", "socketShutdownRequest"] | None: ...

global___MsgRequest = MsgRequest

@typing.final
class MsgResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    SOCKETOPENRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETBINDRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETADDRRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETSENDRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETRECEIVERESPONSE_FIELD_NUMBER: builtins.int
    SOCKETCLOSERESPONSE_FIELD_NUMBER: builtins.int
    GETHOSTBYNAMERESPONSE_FIELD_NUMBER: builtins.int
    GETSERVBYNAMERESPONSE_FIELD_NUMBER: builtins.int
    SOCKETCONNECTRESPONSE_FIELD_NUMBER: builtins.int
    SELECTRESPONSE_FIELD_NUMBER: builtins.int
    SETTINGGETRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETOPTIONSETRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETLISTENRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETACCEPTRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETOPTIONGETRESPONSE_FIELD_NUMBER: builtins.int
    SOCKETSHUTDOWNRESPONSE_FIELD_NUMBER: builtins.int
    INVALIDREQUESTRESPONSE_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def socketOpenResponse(self) -> global___MsgSocketOpenResponse: ...
    @property
    def socketBindResponse(self) -> global___MsgSocketBindResponse: ...
    @property
    def socketAddrResponse(self) -> global___MsgSocketAddrResponse: ...
    @property
    def socketSendResponse(self) -> global___MsgSocketSendResponse: ...
    @property
    def socketReceiveResponse(self) -> global___MsgSocketReceiveResponse: ...
    @property
    def socketCloseResponse(self) -> global___MsgSocketCloseResponse: ...
    @property
    def getHostByNameResponse(self) -> global___MsgGetHostByNameResponse: ...
    @property
    def getServByNameResponse(self) -> global___MsgGetServByNameResponse: ...
    @property
    def socketConnectResponse(self) -> global___MsgSocketConnectResponse: ...
    @property
    def selectResponse(self) -> global___MsgSelectResponse: ...
    @property
    def settingGetResponse(self) -> global___MsgSettingGetResponse: ...
    @property
    def socketOptionSetResponse(self) -> global___MsgSocketOptionSetResponse: ...
    @property
    def socketListenResponse(self) -> global___MsgSocketListenResponse: ...
    @property
    def socketAcceptResponse(self) -> global___MsgSocketAcceptResponse: ...
    @property
    def socketOptionGetResponse(self) -> global___MsgSocketOptionGetResponse: ...
    @property
    def socketShutdownResponse(self) -> global___MsgSocketShutdownResponse: ...
    @property
    def invalidRequestResponse(self) -> global___MsgInvalidRequestResponse: ...
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        socketOpenResponse: global___MsgSocketOpenResponse | None = ...,
        socketBindResponse: global___MsgSocketBindResponse | None = ...,
        socketAddrResponse: global___MsgSocketAddrResponse | None = ...,
        socketSendResponse: global___MsgSocketSendResponse | None = ...,
        socketReceiveResponse: global___MsgSocketReceiveResponse | None = ...,
        socketCloseResponse: global___MsgSocketCloseResponse | None = ...,
        getHostByNameResponse: global___MsgGetHostByNameResponse | None = ...,
        getServByNameResponse: global___MsgGetServByNameResponse | None = ...,
        socketConnectResponse: global___MsgSocketConnectResponse | None = ...,
        selectResponse: global___MsgSelectResponse | None = ...,
        settingGetResponse: global___MsgSettingGetResponse | None = ...,
        socketOptionSetResponse: global___MsgSocketOptionSetResponse | None = ...,
        socketListenResponse: global___MsgSocketListenResponse | None = ...,
        socketAcceptResponse: global___MsgSocketAcceptResponse | None = ...,
        socketOptionGetResponse: global___MsgSocketOptionGetResponse | None = ...,
        socketShutdownResponse: global___MsgSocketShutdownResponse | None = ...,
        invalidRequestResponse: global___MsgInvalidRequestResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["getHostByNameResponse", b"getHostByNameResponse", "getServByNameResponse", b"getServByNameResponse", "id", b"id", "invalidRequestResponse", b"invalidRequestResponse", "payload", b"payload", "selectResponse", b"selectResponse", "settingGetResponse", b"settingGetResponse", "socketAcceptResponse", b"socketAcceptResponse", "socketAddrResponse", b"socketAddrResponse", "socketBindResponse", b"socketBindResponse", "socketCloseResponse", b"socketCloseResponse", "socketConnectResponse", b"socketConnectResponse", "socketListenResponse", b"socketListenResponse", "socketOpenResponse", b"socketOpenResponse", "socketOptionGetResponse", b"socketOptionGetResponse", "socketOptionSetResponse", b"socketOptionSetResponse", "socketReceiveResponse", b"socketReceiveResponse", "socketSendResponse", b"socketSendResponse", "socketShutdownResponse", b"socketShutdownResponse"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["getHostByNameResponse", b"getHostByNameResponse", "getServByNameResponse", b"getServByNameResponse", "id", b"id", "invalidRequestResponse", b"invalidRequestResponse", "payload", b"payload", "selectResponse", b"selectResponse", "settingGetResponse", b"settingGetResponse", "socketAcceptResponse", b"socketAcceptResponse", "socketAddrResponse", b"socketAddrResponse", "socketBindResponse", b"socketBindResponse", "socketCloseResponse", b"socketCloseResponse", "socketConnectResponse", b"socketConnectResponse", "socketListenResponse", b"socketListenResponse", "socketOpenResponse", b"socketOpenResponse", "socketOptionGetResponse", b"socketOptionGetResponse", "socketOptionSetResponse", b"socketOptionSetResponse", "socketReceiveResponse", b"socketReceiveResponse", "socketSendResponse", b"socketSendResponse", "socketShutdownResponse", b"socketShutdownResponse"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["socketOpenResponse", "socketBindResponse", "socketAddrResponse", "socketSendResponse", "socketReceiveResponse", "socketCloseResponse", "getHostByNameResponse", "getServByNameResponse", "socketConnectResponse", "selectResponse", "settingGetResponse", "socketOptionSetResponse", "socketListenResponse", "socketAcceptResponse", "socketOptionGetResponse", "socketShutdownResponse", "invalidRequestResponse"] | None: ...

global___MsgResponse = MsgResponse
