module.exports = {
    swDest: 'build-pwa/ngsw-worker.js',
    globDirectory: 'build-pwa',
    globPatterns: [
        '**/*.js',
        '**/*.html',
        '**/*.wasm',
        '**/*.webmanifest',
        '**/*.css',
        'assets/**/*',
        'assets-pwa/**/*',
        'svg/add-outline.svg',
        'svg/albums-outline.svg',
        'svg/apps-outline.svg',
        'svg/checkmark-circle-outline.svg',
        'svg/chevron-back.svg',
        'svg/clipboard-outline.svg',
        'svg/cog-outline.svg',
        'svg/copy-outline.svg',
        'svg/create-outline.svg',
        'svg/cut-outline.svg',
        'svg/document-outline.svg',
        'svg/download-outline.svg',
        'svg/ellipsis-vertical-outline.svg',
        'svg/eye-off-outline.svg',
        'svg/file-tray-outline.svg',
        'svg/folder-outline.svg',
        'svg/game-controller-outline.svg',
        'svg/help-outline.svg',
        'svg/list-outline.svg',
        'svg/lock-closed-outline.svg',
        'svg/lock-open-outline.svg',
        'svg/log-in-outline.svg',
        'svg/log-out-outline.svg',
        'svg/medkit-outline.svg',
        'svg/phone-portrait-outline.svg',
        'svg/power-outline.svg',
        'svg/radio-button-off-outline.svg',
        'svg/radio-button-on-outline.svg',
        'svg/refresh-outline.svg',
        'svg/reload-outline.svg',
        'svg/share-outline.svg',
        'svg/speedometer-outline.svg',
        'svg/swap-vertical-outline.svg',
        'svg/sync-outline.svg',
        'svg/trash-outline.svg',
        'svg/volume-high-outline.svg',
        'svg/volume-mute-outline.svg',
        'svg/camera-outline.svg',
    ],
    cacheId: 'cloudpilot-pwa',
    mode: 'production',
    clientsClaim: true,
    inlineWorkboxRuntime: true,
    cleanupOutdatedCaches: true,
    maximumFileSizeToCacheInBytes: 10485760,
};
